-- Run this once in Supabase: Dashboard → SQL Editor → New query.
-- Visitors can submit enquiries but cannot read, update, or delete them.

create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 5 and 254),
  level text not null check (level in ('IGCSE Mathematics', 'AS Level Mathematics', 'Not sure yet')),
  message text not null check (char_length(message) between 10 and 2000),
  status text not null default 'new' check (status in ('new', 'contacted', 'converted', 'closed')),
  created_at timestamptz not null default now()
);

alter table public.enquiries enable row level security;

drop policy if exists "Public can submit enquiries" on public.enquiries;
create policy "Public can submit enquiries"
  on public.enquiries
  for insert
  to anon
  with check (true);

-- No SELECT, UPDATE, or DELETE policy is intentionally created.
